# Daniel Nicolas Gisolfi
# 2019-5-23

version: '2'
services:
  dgisolfi-api:
    build: .
    # image: dgisolfi/dgisolfi-api
    ports:
      - "8081:8080"
    container_name: dgisolfi-api
    volumes:
      - /Users/daniel/git/DgisolfiAPI:/usr/src/app
