# Daniel Nicolas Gisolfi
# 2019-5-23

version: '2'
services:
  dgisolfi-api:
    build: .
    ports:
      - "8081:8080"
    container_name: dgisolfi-api
    env_file: .env
    # volumes:
    #   - /Users/daniel/git/DgisolfiAPI:/usr/src/app
  database:
    image: couchdb
    restart: unless-stopped
    container_name: dgisolfi-database
    env_file: .env
    environment:
      COUCHDB_USER: $COUCHDB_USER
      COUCHDB_PASSWORD: $COUCHDB_PASSWORD
    ports:
      - "5984:5984"
    volumes:
      -  ${PWD}/db/data:/opt/couchdb/data
  