openapi: 3.0.0
info:
  title: DgisolfiAPI
  description: A Swagger REST API used to update content on the dgisolfi website
  contact:
    email: Daniel.Gisolfi1@marist.edu
  version: 2.0.0
servers:
- url: "http://dgisolfi.xyz:{port}/{basePath}"
  description: production server
  variables:
    port:
      default: "8080"
    basePath:
      default: /api/
paths:
  /pages/{page}:
    get:
      summary: Returns the content of a page
      operationId: pages_get
      parameters:
      - name: page
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: the content of the page in JSON
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
        "404":
          description: the page was not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
components: {}

